version: "3.8"
name: social-media-app
services:
  spacedb:
    image: mysql
    container_name: spacedb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: milkyway
    ports:
      - "3308:3308"
    volumes:
      - spacedata:/var/lib/mysql
    networks:
      - spacenet

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: spacedb
      MYSQL_ROOT_PASSWORD: milkyway
    ports:
      - "8000:80"
    networks:
      - spacenet
    depends_on:
      - spacedb

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    restart: always
    ports:
      - "8036:8036"
    networks:
      - spacenet


  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8086:8086"
    networks:
      - spacenet
    depends_on:
      - spacedb
      - eureka-server
      - user-service


  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "8100:8100"
    networks:
      - spacenet
    depends_on:
      - spacedb
      - eureka-server

  message-service:
    build: ./message
    container_name: message-service
    restart: always
    ports:
      - "8008:8008"
    networks:
      - spacenet
    depends_on:
      - spacedb
      - eureka-server


volumes:
  spacedata:

networks:
  spacenet:
