apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2024-10-04T11:44:03Z","generation":1,"name":"es","namespace":"trainee5-dev","resourceVersion":"491043","uid":"85053ca9-353e-4aa1-94b5-ab7866d6c4b7"},"spec":{"progressDeadlineSeconds":600,"replicas":0,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"es"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"es"}},"spec":{"containers":[{"env":[{"name":"discovery.type","value":"single-node"},{"name":"ES_JAVA_OPTS","value":"-Xms512m -Xmx512m"}],"image":"docker.elastic.co/elasticsearch/elasticsearch:7.11.1","imagePullPolicy":"IfNotPresent","name":"es","ports":[{"containerPort":9200,"protocol":"TCP"}],"resources":{"limits":{"cpu":"400m","memory":"800Mi"},"requests":{"cpu":"100m","memory":"800Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/usr/share/elasticsearch/data","name":"esdata1"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"esdata1"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-10-04T11:44:04Z","lastUpdateTime":"2024-10-04T11:44:04Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2024-10-04T11:44:03Z","lastUpdateTime":"2024-10-04T11:44:04Z","message":"ReplicaSet \"es-785fcb654c\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-10-04T11:44:03Z"
  generation: 2
  name: es
  namespace: trainee5-dev
  resourceVersion: "2123382"
  uid: 85053ca9-353e-4aa1-94b5-ab7866d6c4b7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: es
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: es
    spec:
      containers:
      - env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
        imagePullPolicy: IfNotPresent
        name: es
        ports:
        - containerPort: 9200
          protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 800Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: esdata1
status:
  conditions:
  - lastTransitionTime: "2024-10-04T11:44:04Z"
    lastUpdateTime: "2024-10-04T11:44:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-10-04T11:44:03Z"
    lastUpdateTime: "2024-10-04T11:44:04Z"
    message: ReplicaSet "es-785fcb654c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
